# Generated by Django 4.2.6 on 2023-10-19 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='status_id',
            new_name='status',
        ),
    ]
